export const copy = {
  appTitle: "Server configuration",
  loading: "Loading configuration…",
  formTab: "Form",
  rawTab: "Raw",
  filesHeading: "Configuration files",
  inspectorHeading: "Changes & validation",
  noChanges: "No pending changes",
  rawChanged: "Raw configuration changed",
  unknownKeys: "Unknown keys: Preserved",
  restartRequired: "Restart required",
  stopBeforeSave: "Stop the server before saving configuration files that it may rewrite.",
  noRestartRequired: "No restart required",
  save: "Save changes",
  saving: "Saving…",
  saved: "Saved and verified",
  conflict: "Remote file changed. Reload before saving.",
  rawLabel: "Raw configuration",
  validationHeading: "Validation",
  valid: "Configuration is valid",
  secretChanged: "Secret changed",
  fileFormat: "Format",
} as const;
