export const copy = {
  appTitle: "Server configuration",
  loading: "Loading configuration…",
  formTab: "Form",
  rawTab: "Raw",
  filesHeading: "Configuration files",
  restartRequired: "Restart required",
  restartAfterSave: "Restart required after saving",
  save: "Save changes",
  saving: "Saving…",
  saved: "Saved and verified",
  conflict: "Remote file changed. Reload before saving.",
  rawLabel: "Raw configuration",
  fileFormat: "Format",
} as const;
