#Dockerhub does not allow for setting of build args :/
ARG IMAGE=openjdk:26-ea-21-slim
FROM $IMAGE
WORKDIR /app

RUN apt update
RUN apt install -y ca-certificates wget jq moreutils htop procps nano net-tools unzip curl
RUN rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash druid

USER druid
