#Dockerhub does not allow for setting of build args :/
ARG IMAGE=openjdk:26-ea-17-slim
FROM $IMAGE
WORKDIR /app

RUN apt update
RUN apt install -y ca-certificates wget jq moreutils htop procps nano net-tools unzip
RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
RUN chmod +x /usr/bin/yq

#RUN wget "https://github.com/highcard-dev/druidd/releases/download/latest/druid_linux_386.deb" -O "druidd.deb"
#RUN apt install ./druidd.deb

RUN useradd -ms /bin/bash druid

ARG CACHEBUST=1 
RUN wget -O /usr/bin/druid https://github.com/highcard-dev/druid-cli/releases/latest/download/druid
RUN wget -O /usr/bin/druid_rcon https://github.com/highcard-dev/druid-cli/releases/latest/download/druid_rcon
RUN wget -O /usr/bin/druid_rcon_web_rust https://github.com/highcard-dev/druid-cli/releases/latest/download/druid_rcon_web_rust
RUN wget -O /entrypoint.sh https://github.com/highcard-dev/druid-cli/releases/latest/download/entrypoint.sh

RUN chmod +x /usr/bin/druid
RUN chmod +x /usr/bin/druid_rcon
RUN chmod +x /usr/bin/druid_rcon_web_rust
RUN chmod +x /entrypoint.sh

USER druid

ENTRYPOINT [ "/entrypoint.sh" ]