name: Build single LinuxGSM images
on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image"
        required: true
jobs:
  build-lgsm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SCROLL_REGISTRY_USER }}
          password: ${{ secrets.SCROLL_REGISTRY_PASSWORD }}
      - name: Build all LGSM games
        run: cd .docker/linuxgsm/ && bash build-push-docker-images.sh ${{ github.event.inputs.image }}
