name: Docker
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
   build-deploy:
    runs-on: self-hosted
    env:
       REGISTRY_ENDPOINT: https://${{ secrets.S3_API_KEY }}:${{ secrets.S3_API_SECRET }}@${{ secrets.S3_ENDPOINT }}
    steps:
      - run: sudo apt install moreutils -y
      - uses: actions/checkout@v3
      - name: Download latest.json
        run: mc cp scrolls/druid-scrolls-staging/latest.json old-latest.json || true
      - name: Building new files
        run: sh build-changed-scrolls.sh
      - name: Pushing new scrolls i18n
        run: sh .ci/push-i18n.sh
      - name: Pushing new scrolls
        run: sh .ci/push.sh