name: Build Linux GSM images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build-lgsm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SCROLL_REGISTRY_USER }}
          password: ${{ secrets.SCROLL_REGISTRY_PASSWORD }}
      - name: Build all LGSM games
        run: cd .docker/linuxgsm/ && bash build-docker-images.sh
