name: Docker
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
   build-deploy:
    runs-on: self-hosted
    env:
      MC_HOST_scrolls: https://${{ secrets.S3_API_KEY }}:${{ secrets.S3_API_SECRET }}@${{ secrets.S3_ENDPOINT }}
    steps:
      - run: sudo apt install moreutils -y
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download latest.json
        run: mc cp scrolls/druid-scrolls-staging/latest.json old-latest.json || true
      - run: sh find-changed-scrolls.sh
        name: Building new files
      - name: Pushing new scrolls
        run: sh .ci/push.sh