name: Fetch Spigot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build-spigot:
    strategy:
      matrix:
        version:
          [
            { java-version: "16", spigot-version: "1.17" },
            { java-version: "16", spigot-version: "1.17.1" },
            { java-version: "17", spigot-version: "1.18" },
            { java-version: "17", spigot-version: "1.18.1" },
            { java-version: "17", spigot-version: "1.18.2" },
            { java-version: "17", spigot-version: "1.19" },
            { java-version: "17", spigot-version: "1.19.1" },
            { java-version: "17", spigot-version: "1.19.2" },
            { java-version: "17", spigot-version: "1.19.3" },
            { java-version: "17", spigot-version: "1.19.4" },
            { java-version: "17", spigot-version: "1.20.1" },
            { java-version: "17", spigot-version: "1.20.2" },
            { java-version: "17", spigot-version: "1.20.4" },
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21"
      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft" # See 'Supported distributions' for available options
          java-version: "${{ matrix.version.java-version }}"
      - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - run: java -jar BuildTools.jar --rev ${{ matrix.version.spigot-version }}
      - run: mkdir -p spigot && mv spigot-${{ matrix.version.spigot-version }}.jar spigot/spigot-${{ matrix.version.spigot-version }}.jar
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://s3.eu-central-1.wasabisys.com/
          AWS_REGION: "eu-central-1"
          SOURCE_DIR: spigot
          DEST_DIR: minecraft/spigot
