name: Release All Pipeline
on:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      SCROLL_REGISTRY_ENDPOINT: ${{ secrets.SCROLL_REGISTRY_ENDPOINT }}
      SCROLL_REGISTRY_API_KEY: ${{ secrets.SCROLL_REGISTRY_API_KEY }}
      SCROLL_REGISTRY_API_SECRET: ${{ secrets.SCROLL_REGISTRY_API_SECRET }}
      SCROLL_REGISTRY_BUCKET: ${{ secrets.SCROLL_REGISTRY_BUCKET_LIVE }}
    steps:
      - uses: actions/checkout@v3
      - name: Get registry binary
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "highcard-dev/backend-monorepo-go"
          latest: true
          fileName: "scrolls-registry"
          token: ${{ secrets.GO_REPO_TOKEN }}
      - run: chmod +x ./scrolls-registry
      - name: Building only version updates
        run: ./scrolls-registry build -d ./scrolls
      - name: Pushing new scrolls
        shell: bash
        run: |
          ./scrolls-registry push -d ./scrolls -t packages
          ./scrolls-registry push -d ./scrolls -t registry-index
      - name: Pushing new scrolls i18n
        run: ./scrolls-registry push -d ./scrolls -t translations
      - name: Cleanup
        run: ./scrolls-registry clean
