name: Release Changed Pipeline
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      SCROLL_REGISTRY_ENDPOINT: ${{ secrets.SCROLL_REGISTRY_ENDPOINT }}
      SCROLL_REGISTRY_API_KEY: ${{ secrets.SCROLL_REGISTRY_API_KEY }}
      SCROLL_REGISTRY_API_SECRET: ${{ secrets.SCROLL_REGISTRY_API_SECRET }}
      SCROLL_REGISTRY_BUCKET: ${{ secrets.SCROLL_REGISTRY_BUCKET_STAGING }}
    steps:
      - uses: actions/checkout@v3
      - name: Get registry binary
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "highcard-dev/backend-monorepo-go"
          latest: true
          fileName: "druid"
          token: ${{ secrets.GO_REPO_TOKEN }}
      - run: chmod +x ./druid
      - name: Login to registry
        run: ./druid registry login --host ${{ secrets.SCROLL_REGISTRY_HOST }} --user ${{ secrets.SCROLL_REGISTRY_USER }} --password ${{ secrets.SCROLL_REGISTRY_PASSWORD }}
      - name: Pushing new scrolls
        shell: bash
        run: |
          ./druid registry push ./scrolls/mc/mc-sp/1.17 registry-1.docker.io/highcard/scroll-minecraft-spigot:1.17-latest
          ./druid registry push ./scrolls/mc/mc-sp/1.18 registry-1.docker.io/highcard/scroll-minecraft-spigot:1.18-latest
          ./druid registry push ./scrolls/mc/mc-sp/1.19 registry-1.docker.io/highcard/scroll-minecraft-spigot:1.19-latest
          ./druid registry push ./scrolls/mc/rust-oxide registry-1.docker.io/highcard/scroll-rust-oxide:latest
          ./druid registry push ./scrolls/mc/rust-vanilla registry-1.docker.io/highcard/scroll-rust-vanilla:latest
