name: Release Changed Pipeline
permissions:
  contents: read
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      SCROLL_REGISTRY_ENDPOINT: ${{ secrets.SCROLL_REGISTRY_ENDPOINT }}
      SCROLL_REGISTRY_API_KEY: ${{ secrets.SCROLL_REGISTRY_API_KEY }}
      SCROLL_REGISTRY_API_SECRET: ${{ secrets.SCROLL_REGISTRY_API_SECRET }}
      SCROLL_REGISTRY_BUCKET: ${{ secrets.SCROLL_REGISTRY_BUCKET_STAGING }}
    steps:
      - uses: actions/checkout@v3
      - name: Get registry binary
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "highcard-dev/backend-monorepo-go"
          latest: true
          fileName: "scrolls-registry"
          token: ${{ secrets.GO_REPO_TOKEN }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: chmod +x ./scrolls-registry
      - name: Building only version updates
        run: ./scrolls-registry build -d ./scrolls -c
      - name: Pushing new scrolls
        shell: bash
        run: |
          ./scrolls-registry push -d ./scrolls -t packages
          ./scrolls-registry push -d ./scrolls -t registry-index
      - name: Pushing new scrolls i18n
        run: ./scrolls-registry push -d ./scrolls -t translations
      - name: Cleanup
        run: ./scrolls-registry clean
