name: Release Changed Pipeline
on:
  workflow_dispatch:
  push:
    branches: [master]
    tags: [v*]
permissions:
  contents: read
jobs:
  build-deploy:
    uses: ./.github/workflows/scroll-lifecycle.yml
    with:
      public: true
