name: Release Changed Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      SCROLL_REGISTRY_ENDPOINT: ${{ secrets.SCROLL_REGISTRY_ENDPOINT }}
      SCROLL_REGISTRY_API_KEY: ${{ secrets.SCROLL_REGISTRY_API_KEY }}
      SCROLL_REGISTRY_API_SECRET: ${{ secrets.SCROLL_REGISTRY_API_SECRET }}
      SCROLL_REGISTRY_BUCKET: ${{ secrets.SCROLL_REGISTRY_BUCKET_STAGING }}
    steps:
      - uses: actions/checkout@v3
      - name: Get registry binary
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "highcard-dev/monorepo"
          latest: true
          fileName: "druid"
          token: ${{ secrets.GO_REPO_TOKEN }}
      - run: chmod +x ./druid
      - name: Login to registry
        run: ./druid registry login --host ${{ secrets.SCROLL_REGISTRY_HOST }} --user ${{ secrets.SCROLL_REGISTRY_USER }} --password ${{ secrets.SCROLL_REGISTRY_PASSWORD }}
      - name: Pushing new scrolls
        shell: bash
        run: |
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.17 -p main=25565 -p rcon=25575 -i highcard/druidd-java:16
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.17.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:16
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.18 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.18.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.18.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.3 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.20.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.20.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.20.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.17 -p main=25565 -p rcon=25575 -i highcard/druidd-java:16
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.17.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:16
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.18 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.18.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.18.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.3 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.20.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.20.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.20.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.17 -p main=25565 -p rcon=25575 -i highcard/druidd-java:16
          ./druid registry push ./scrolls/minecraft/papermc/1.17.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:16
          ./druid registry push ./scrolls/minecraft/papermc/1.18.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.18.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.19 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.19.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.19.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.19.3 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.19.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.20.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.20.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/papermc/1.20.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.17.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:16
          ./druid registry push ./scrolls/minecraft/forge/1.18 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.18.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.18.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.19 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.19.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.19.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.19.3 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.19.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:17
          ./druid registry push ./scrolls/minecraft/forge/1.20 -p main=25565 -p rcon=25575 -i highcard/druidd-java:20
          ./druid registry push ./scrolls/minecraft/forge/1.20.1 -p main=25565 -p rcon=25575 -i highcard/druidd-java:20
          ./druid registry push ./scrolls/minecraft/forge/1.20.2 -p main=25565 -p rcon=25575 -i highcard/druidd-java:20
          ./druid registry push ./scrolls/minecraft/forge/1.20.3 -p main=25565 -p rcon=25575 -i highcard/druidd-java:20
          ./druid registry push ./scrolls/minecraft/forge/1.20.4 -p main=25565 -p rcon=25575 -i highcard/druidd-java:20
          ./druid registry push ./scrolls/minecraft/cuberite/latest -p main=25565 -p webpanel=8080 -i highcard/druidd-ubuntu
          ./druid registry push ./scrolls/rust/rust-oxide/latest -p main=28015/udp -p rcon -p rustplus -i highcard/druidd-steamcmd
          ./druid registry push ./scrolls/rust/rust-vanilla/latest -p main=28015/udp -p rcon -p rustplus -i highcard/druidd-steamcmd
          ./druid registry push ./scrolls/lgsm/pwserver -p main=8211/udp -p rcon=25575 -i highcard/druidd-lgsm:pw -m
          ./druid registry push ./scrolls/lgsm/arkserver -p main=7777/udp -p raw-udp=7777/udp -p query=27015/udp -p rcon=27020 -i highcard/druidd-lgsm:ark -m

          ./druid registry push ./scrolls/lgsm/csgoserver -p query=27005/udp -p main=27015/udp -p sourcetv=27020/udp -p steam=27015 -i highcard/druidd-lgsm:csgo -m
          ./druid registry push ./scrolls/lgsm/untserver -p main=27015/udp -p mainv6=27016 -i highcard/druidd-lgsm:unt -m
          ./druid registry push ./scrolls/lgsm/dayzserver -p main=2302/udp -p battle-eye=2304/udp -p query=27016/udp -i highcard/druidd-lgsm:dayz -m
          ./druid registry push ./scrolls/lgsm/sdtdserver -p main=26900/udp -p main2=26902/udp -p maintcp=26900 -i highcard/druidd-lgsm:sdtd -m
          ./druid registry push ./scrolls/lgsm/terrariaserver -p todo=8211/udp -i highcard/druidd-lgsm:terraria -m
          ./druid registry push ./scrolls/lgsm/gmodserver -p todo=8211/udp  -i highcard/druidd-lgsm:gmod -m
      - name: Push Meta
        run: |
          ./druid registry push meta registry-1.docker.io/highcard/scroll-minecraft-spigot ./scrolls/minecraft/minecraft-spigot/.meta
          ./druid registry push meta registry-1.docker.io/highcard/scroll-minecraft-vanilla ./scrolls/minecraft/minecraft-vanilla/.meta
          ./druid registry push meta registry-1.docker.io/highcard/scroll-minecraft-paper ./scrolls/minecraft/papermc/.meta
          ./druid registry push meta registry-1.docker.io/highcard/scroll-minecraft-forge ./scrolls/minecraft/forge/.meta
          ./druid registry push meta registry-1.docker.io/highcard/scroll-minecraft-cuberite ./scrolls/minecraft/cuberite/.meta
          ./druid registry push meta registry-1.docker.io/highcard/scroll-rust-oxide ./scrolls/rust/rust-oxide/.meta
          ./druid registry push meta registry-1.docker.io/highcard/scroll-rust-vanilla ./scrolls/rust/rust-vanilla/.meta
