name: Release Changed Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      SCROLL_REGISTRY_ENDPOINT: ${{ secrets.SCROLL_REGISTRY_ENDPOINT }}
      SCROLL_REGISTRY_API_KEY: ${{ secrets.SCROLL_REGISTRY_API_KEY }}
      SCROLL_REGISTRY_API_SECRET: ${{ secrets.SCROLL_REGISTRY_API_SECRET }}
      SCROLL_REGISTRY_BUCKET: ${{ secrets.SCROLL_REGISTRY_BUCKET_STAGING }}
    steps:
      - uses: actions/checkout@v3
      - name: Get registry binary
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "highcard-dev/backend-monorepo-go"
          latest: true
          fileName: "druid"
          token: ${{ secrets.GO_REPO_TOKEN }}
      - run: chmod +x ./druid
      - name: Login to registry
        run: ./druid registry login --host ${{ secrets.SCROLL_REGISTRY_HOST }} --user ${{ secrets.SCROLL_REGISTRY_USER }} --password ${{ secrets.SCROLL_REGISTRY_PASSWORD }}
      - name: Pushing new scrolls
        shell: bash
        run: |
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.17
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.17.1
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.18
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.18.1
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.18.2
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.1
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.2
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.3
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.19.4
          ./druid registry push ./scrolls/minecraft/minecraft-spigot/1.20.1
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.17
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.17.1
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.18
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.18.1
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.18.2
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.1
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.2
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.3
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.19.4
          ./druid registry push ./scrolls/minecraft/minecraft-vanilla/1.20.1
          ./druid registry push ./scrolls/minecraft/papermc/1.17
          ./druid registry push ./scrolls/minecraft/papermc/1.17.1
          ./druid registry push ./scrolls/minecraft/papermc/1.18.1
          ./druid registry push ./scrolls/minecraft/papermc/1.18.2
          ./druid registry push ./scrolls/minecraft/papermc/1.19
          ./druid registry push ./scrolls/minecraft/papermc/1.19.1
          ./druid registry push ./scrolls/minecraft/papermc/1.19.2
          ./druid registry push ./scrolls/minecraft/papermc/1.19.3
          ./druid registry push ./scrolls/minecraft/papermc/1.19.4
          ./druid registry push ./scrolls/minecraft/papermc/1.20.1
          ./druid registry push ./scrolls/minecraft/cuberite/latest
          ./druid registry push ./scrolls/rust/rust-oxide/latest
          ./druid registry push ./scrolls/rust/rust-vanilla/latest
