name: Build Spigot
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build-spigot:
    strategy:
      matrix:
        version: [{ java-version: "16", spigot-version: "1.17.1" }]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft" # See 'Supported distributions' for available options
          java-version: "${{ matrix.version.java-version }}"
      - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - run: java -jar BuildTools.jar --rev ${{ matrix.version.spigot-version }}
