name: Build Spigot
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build-spigot:
    strategy:
      matrix:
        version:
          [
            { java-version: "16", spigot-version: "1.17" },
            { java-version: "16", spigot-version: "1.17.1" },
            { java-version: "17", spigot-version: "1.18" },
            { java-version: "17", spigot-version: "1.18.1" },
            { java-version: "17", spigot-version: "1.18.2" },
            { java-version: "17", spigot-version: "1.19" },
            { java-version: "17", spigot-version: "1.19.1" },
            { java-version: "17", spigot-version: "1.19.2" },
            { java-version: "17", spigot-version: "1.19.3" },
            { java-version: "17", spigot-version: "1.19.4" },
            { java-version: "17", spigot-version: "1.20.1" },
          ]
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft" # See 'Supported distributions' for available options
          java-version: "${{ matrix.version.java-version }}"
      - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - run: java -jar BuildTools.jar --rev ${{ matrix.version.spigot-version }}
